### ISSUE TITLE
Notebook no longer working

### ISSUE THREAD

**Issue by chamanbabangogo** [EyadNasr/Coursera-Courses-to-Google-Drive#1]
It was working 2 weeks back,
Today I checked and i am getting this error

coursera_dl version 0.11.5
Downloading class: project-management-foundations?specialization=google-project-management (1 / 1)
Error 400 Client Error: Bad Request for url: https://api.coursera.org/api/onDemandCourseMaterials.v2/?q=slug&slug=project-management-foundations?specialization=google-project-management&includes=modules%2Clessons%2CpassableItemGroups%2CpassableItemGroupChoices%2CpassableLessonElements%2Citems%2Ctracks%2CgradePolicy&&fields=moduleIds%2ConDemandCourseMaterialModules.v1(name%2Cslug%2Cdescription%2CtimeCommitment%2ClessonIds%2Coptional%2ClearningObjectives)%2ConDemandCourseMaterialLessons.v1(name%2Cslug%2CtimeCommitment%2CelementIds%2Coptional%2CtrackId)%2ConDemandCourseMaterialPassableItemGroups.v1(requiredPassedCount%2CpassableItemGroupChoiceIds%2CtrackId)%2ConDemandCourseMaterialPassableItemGroupChoices.v1(name%2Cdescription%2CitemIds)%2ConDemandCourseMaterialPassableLessonElements.v1(gradingWeight%2CisRequiredForPassing)%2ConDemandCourseMaterialItems.v2(name%2Cslug%2CtimeCommitment%2CcontentSummary%2CisLocked%2ClockableByItem%2CitemLockedReasonCode%2CtrackId%2ClockedStatus%2CitemLockSummary)%2ConDemandCourseMaterialTracks.v1(passablesCount)&showLockedItems=true getting page https://api.coursera.org/api/onDemandCourseMaterials.v2/?q=slug&slug=project-management-foundations?specialization=google-project-management&includes=modules%2Clessons%2CpassableItemGroups%2CpassableItemGroupChoices%2CpassableLessonElements%2Citems%2Ctracks%2CgradePolicy&&fields=moduleIds%2ConDemandCourseMaterialModules.v1(name%2Cslug%2Cdescription%2CtimeCommitment%2ClessonIds%2Coptional%2ClearningObjectives)%2ConDemandCourseMaterialLessons.v1(name%2Cslug%2CtimeCommitment%2CelementIds%2Coptional%2CtrackId)%2ConDemandCourseMaterialPassableItemGroups.v1(requiredPassedCount%2CpassableItemGroupChoiceIds%2CtrackId)%2ConDemandCourseMaterialPassableItemGroupChoices.v1(name%2Cdescription%2CitemIds)%2ConDemandCourseMaterialPassableLessonElements.v1(gradingWeight%2CisRequiredForPassing)%2ConDemandCourseMaterialItems.v2(name%2Cslug%2CtimeCommitment%2CcontentSummary%2CisLocked%2ClockableByItem%2CitemLockedReasonCode%2CtrackId%2ClockedStatus%2CitemLockSummary)%2ConDemandCourseMaterialTracks.v1(passablesCount)&showLockedItems=true
The server replied: {"msg":"Routing error: Improperly formatted value for parameter 'slug'"}
HTTPError 400 Client Error: Bad Request for url: https://api.coursera.org/api/onDemandCourseMaterials.v2/?q=slug&slug=project-management-foundations?specialization=google-project-management&includes=modules%2Clessons%2CpassableItemGroups%2CpassableItemGroupChoices%2CpassableLessonElements%2Citems%2Ctracks%2CgradePolicy&&fields=moduleIds%2ConDemandCourseMaterialModules.v1(name%2Cslug%2Cdescription%2CtimeCommitment%2ClessonIds%2Coptional%2ClearningObjectives)%2ConDemandCourseMaterialLessons.v1(name%2Cslug%2CtimeCommitment%2CelementIds%2Coptional%2CtrackId)%2ConDemandCourseMaterialPassableItemGroups.v1(requiredPassedCount%2CpassableItemGroupChoiceIds%2CtrackId)%2ConDemandCourseMaterialPassableItemGroupChoices.v1(name%2Cdescription%2CitemIds)%2ConDemandCourseMaterialPassableLessonElements.v1(gradingWeight%2CisRequiredForPassing)%2ConDemandCourseMaterialItems.v2(name%2Cslug%2CtimeCommitment%2CcontentSummary%2CisLocked%2ClockableByItem%2CitemLockedReasonCode%2CtrackId%2ClockedStatus%2CitemLockSummary)%2ConDemandCourseMaterialTracks.v1(passablesCount)&showLockedItems=true

**Comment by EyadNasr** [comment]
I tried to download your course using this link "https://www.coursera.org/professional-certificates/google-project-management"

**Comment by EyadNasr** [comment]
I tried to download your course using this link "https://www.coursera.org/professional-certificates/google-project-management" and chose the "Specialization or Professional Certificate" option... and it worked just fine.
see here >>> https://drive.google.com/drive/folders/18jNuBdQ6KSfwkn1lwQD8n_c0SsbydUDB
Try to log out then log in and copy the new CAUTH value

**Comment by chamanbabangogo** [comment]
hmm.. Let me check again,
I will update status again..

**Comment by chamanbabangogo** [comment]
Still not working for me... same course URL & same Specialization or Professional Certificate option..( tried switching this as well)

  File "<ipython-input-8-6f80d07825b5>", line 20
    Specialization or Professional Certificate = False #@param {type:"boolean"}
                                             ^
SyntaxError: invalid syntax

  File "<ipython-input-8-6f80d07825b5>", line 20
    Specialization or Professional Certificate = True#@param {type:"boolean"}
                                             ^
SyntaxError: invalid syntax



Even tried with another login id as well as providing those details along with CAUTH information in colab notebook.

.. well, soon i will create screen recording for same and post link here...

**Comment by EyadNasr** [comment]
yeah sorry for that syntax error, just fixed it

**Comment by chamanbabangogo** [comment]
Now, I am getting this :

NameError                                 Traceback (most recent call last)
<ipython-input-4-e7aa0f308f74> in <module>()
     64   print('Folder created:', download_folder)
     65 except FileExistsError : print("Folder exists:", download_folder)
---> 66 if Specialization:
     67   sp = '--specialization'
     68   folder_path = download_folder + Course_Name

NameError: name 'Specialization' is not defined

---

**Comment by EyadNasr** [comment]
fixed it

**Comment by chamanbabangogo** [comment]
And it is working now :)
Thanks a lottttttttttttttttttttttttttttttttttttt 👍
